class Config:
    DEBUG = True
    SERVER_NAME = 'localhost:5000'

    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_HTTPONLY = True
    TEMPLATES_AUTO_RELOAD = True

    PREFERRED_URL_SCHEME = 'http'
    PROPAGATE_EXCEPTIONS = True
    JSONIFY_PRETTYPRINT_REGULAR = True

    MAX_CONTENT_LENGTH = 16 * 1024 * 1024  # 16 MB
    MAX_COOKIE_SIZE = 4096  # 4KB
